<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LP-PC0MQFYK" ignored="0" name="Default test" tests="16" failures="1" timestamp="24 Jul 2018 10:58:12 GMT" time="26.841" errors="0">
  <testcase name="LoginPageFreeCRMTitleTest" time="17.073" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="SignUpbutton" time="6.24" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="SignUpGetTitleTest" time="0.012" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="SignUpEditionDropdownValuesTest" time="0.092" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="VerifyAllFieldsAreRequiredLabelTest" time="0.036" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="VerifyTermsAndConditionsLinkTest" time="0.034" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="VerifyDisabledIAgreeCheckboxTest" time="0.044" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="VerifyDisabledSubmitbuttonTest" time="0.037" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="SignUpEditionDropdownTest" time="0.175" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="SignUpFormTest" time="1.534" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="VerifyEnabledIAgreeCheckboxTest" time="0.038" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="ClickingOnCheckboxTest" time="0.084" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="VerifyEnabledSubmitbuttonTest" time="0.028" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="SubmitbuttonTest" time="0.731" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
  <testcase name="VerifyAlert" time="0.02" classname="Com.crm.qa.TestCases.SignUpPageTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	Alert Msg Is Getting Displayed Wrong expected [Errors were encountered: This username is already in use by another user. Please select a different username.] but found [Errors were encountered: 

This username is already in use by another user. Please select a different username.
]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
Alert Msg Is Getting Displayed Wrong expected [Errors were encountered: This username is already in use by another user. Please select a different username.] but found [Errors were encountered: 

This username is already in use by another user. Please select a different username.
]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at Com.crm.qa.TestCases.SignUpPageTest.VerifyAlert(SignUpPageTest.java:153)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- VerifyAlert -->
  <testcase name="backToLoginPage" time="0.606" classname="Com.crm.qa.TestCases.SignUpPageTest"/>
</testsuite> <!-- Default test -->
